routes/web.php
<?php
// \Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {
//     echo'<pre>';
//     var_dump($query->sql);
//     // var_dump($query->bindings);
//     // var_dump($query->time);
//     echo'</pre>';
// });


/*** STORE SECTION ***/
Route::get('/store', 'Store\StoreController@index')->name('store');

/* Category */
Route::get('/category/{category}/{category_url_key}', 'Store\CategoriesController@index')->name('store.category');

/* Product */
Route::get('/', 'Store\ProductsController@productList')->name('store.product.list');
Route::get('/product/{product}/quickview', 'Store\ProductsController@quickView')->name('store.product.quickview');
Route::get('/product/{product}/{product_url_key?}', 'Store\ProductsController@singleProduct')->name('store.product');

/* Cart */
Route::get('/cart', 'Store\CartController@cart')->name('store.cart');
Route::get('/cart/info', 'Store\CartController@info')->name('store.cart.info');
Route::post('/cart/add/{product}', 'Store\CartController@add')->name('store.cart.add');
Route::post('/cart/remove/{product}', 'Store\CartController@remove')->name('store.cart.remove');
Route::get('/cart/update/{product}', 'Store\CartController@update')->name('store.cart.update');

/* WishList */
Route::get('/wishlist', 'Store\WishListController@wishlist')->name('store.wishlist');
Route::get('/wishlist/add/{product}', 'Store\WishListController@add')->name('store.wishlist.add');
Route::get('/wishlist/remove/{product}', 'Store\WishListController@remove')->name('store.wishlist.remove');

/* Checkout */
Route::get('/checkout', 'Store\CheckoutController@checkout')->name('store.checkout');
Route::post('/checkout/confirm', 'Store\CheckoutController@confirm')->name('store.checkout.confirm');
Route::get('/checkout/success', 'Store\CheckoutController@success')->name('store.checkout.success');

/* Brand */
Route::get('/brand/{brand}/{brand_url_key?}', 'Store\BrandsController@brand')->name('store.brand');

/* Page */
Route::get('/page/{page_url_key}', 'Store\PagesController@index')->name('store.page');

/* Blog */
Route::get('/article/{article}/{url_key?}', 'Store\ArticlesController@singleArticle')->name('store.article');
Route::get('/articles', 'Store\ArticlesController@articleList')->name('store.article.list');

/*** BACKEND SECTION ***/

/* Dashboard */
Route::get('/admin', 'Backend\SettingsController@index')->name('dashboard.index');

/* Settings */
Route::get('/admin/settings', 'Backend\SettingsController@index')->name('settings.index');
Route::put('/admin/settings', 'Backend\SettingsController@update')->name('settings.update');

/* Categories */
Route::resource('/admin/categories', 'Backend\CategoriesController', ['except' => ['show']]);
Route::get('/admin/categories/autocomplete', 'Backend\CategoriesController@autocomplete')
    ->name('categories.autocomplete');
Route::get('/admin/categories/datatable', 'Backend\CategoriesController@datatable')
    ->name('categories.datatable');

/* Products */
Route::resource('/admin/products', 'Backend\ProductsController', ['except' => ['show']]);
Route::get('/admin/products/datatable', 'Backend\ProductsController@datatable')
    ->name('products.datatable');
Route::get('/admin/products/autocomplete', 'Backend\ProductsController@autocomplete')
    ->name('products.autocomplete');

/* Brands */
Route::resource('/admin/brands', 'Backend\BrandsController', ['except' => ['show']]);
Route::get('/admin/brands/autocomplete', 'Backend\BrandsController@autocomplete')
    ->name('brands.autocomplete');
Route::get('/admin/brands/datatable', 'Backend\BrandsController@datatable')
    ->name('brands.datatable');

/* Banners */
// 2 Words
Route::get('/admin/banner/2words', 'Backend\Module\TwoWordsController@index')
    ->name('banner.2words');
Route::post('/admin/banner/2words', 'Backend\Module\TwoWordsController@save');
// Top 5
Route::get('/admin/banner/top5', 'Backend\Module\Top5Controller@index')
    ->name('banner.top5');
Route::post('/admin/banner/top5', 'Backend\Module\Top5Controller@save');
// Carousel
Route::get('/admin/banner/carousel', 'Backend\Module\CarouselController@index')
    ->name('banner.carousel');
Route::post('/admin/banner/carousel', 'Backend\Module\CarouselController@save');
// Collection
Route::get('/admin/banner/collection', 'Backend\Module\CollectionController@index')
    ->name('banner.collection');
Route::post('/admin/banner/collection', 'Backend\Module\CollectionController@save');

/* Pages */
Route::resource('/admin/pages', 'Backend\PagesController', ['except' => ['show']]);
Route::get('/admin/pages/datatable', 'Backend\PagesController@datatable')
    ->name('pages.datatable');

/* Articles */
Route::resource('/admin/articles', 'Backend\ArticlesController', ['except' => ['show']]);
Route::get('/admin/articles/datatable', 'Backend\ArticlesController@datatable')
    ->name('articles.datatable');
Route::get('/admin/articles/autocomplete', 'Backend\ArticlesController@autocomplete')
    ->name('articles.autocomplete');

app/Http/Controllers/Backend/ArticlesController.php
<?php

namespace WBstore\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\Datatables\Datatables;
use WBstore\Http\Requests\StoreArticleRequest;
use WBstore\Http\Requests\UpdateArticleRequest;
use WBstore\Article;
use WBstore\ArticleDescription;
use Carbon\Carbon;

class ArticlesController extends Controller
{
    public function index(Article $articles)
    {
        return view('backend.articles.index')->with('articles', $articles->paginate(10));
    }

    public function create(Article $article)
    {
        return view('backend.articles.create', compact('article'));
    }

    public function store(StoreArticleRequest $request, article $article)
    {
        $data = $request->all();

        DB::transaction(function() use ($article, $data) {
            $article = $article->create($data);
            $article->description()->create($data['description']);

            if (!empty($data['related_articles'])) {
                $article->relatedArticles()->attach($data['related_articles']);  
            }

            if (!empty($data['related_products'])) {
                $article->relatedProducts()->attach($data['related_products']);  
            }
        });

        return redirect()->route('articles.index')
            ->with('success', 'Статья "'. $data['description']['title'] .'"  успешно сохранена!');
    }

    public function edit(Article $article)
    {
        $article->relatedArticlesById = $article->relatedArticles->pluck('description.title', 'id')->all();
        $article->relatedProductsById = $article->relatedProducts->pluck('description.title', 'id')->all();

        return view('backend.articles.edit', compact('article'));
    }

    public function update(UpdateArticleRequest $request, article $article)
    {
        $data = $request->all();

        DB::transaction(function() use ($article, $data) {
            $article->update($data);
            $article->description()->update($data['description']);

            $article->relatedArticles()->detach();
            if (!empty($data['related_articles'])) {
                $article->relatedArticles()->attach($data['related_articles']);  
            }

            $article->relatedProducts()->detach();
            if (!empty($data['related_products'])) {
                $article->relatedProducts()->attach($data['related_products']);  
            }
        });

        return redirect()->route('articles.index')
            ->with('success', 'Статья "'. $data['description']['title'] .'"  успешно обновлена!');
    }

    public function confirm(Article $article)
    {
        return view('backend.articles.confirm', compact('article'));
    }

    public function destroy(Article $article)
    {
        if ($article) {
            $article->delete();
        }
    }

    public function datatable()
    {
        if (request()->ajax()) {
            return Datatables::of(Article::with(['description' => function($q) {
                        $q->select('article_id', 'title');
                }]))
                ->filter(function ($query) {
                    if (!empty(request('search')['value'])) {
                        $query->whereHas('description', function($q) {
                            $q->where('title', 'like', "%" . request('search')['value'] . "%");
                        });
                    }
                })
                ->editColumn('published_at', function($aritcle) {
                    $now = Carbon::now();

                    if ($aritcle->published_at < $now) {
                        return $aritcle->present()->published_date;
                    } elseif ($aritcle->published_at > $now) {
                        return 'Ожидает: ' . $aritcle->present()->published_date('%d %B %Y, %I:%M');
                    }

                    return 'Не опупликован';
                })
                ->make(true);
        }
    }

    public function autocomplete(Request $request)
    {
        if (request()->ajax()) {
            $data = [];

            if ($request->has('term', 'page')) {

                $page = $request->page;
                $resultCount = 10;
                $offset = ($page - 1) * $resultCount;

                $search = $request->term;

                $data = ArticleDescription::select("article_id as id", "title")->where('title', 'LIKE', "%$search%")->orderBy('title')->skip($offset)->take($resultCount)->get();

                $count = ArticleDescription::where('title', 'LIKE', "%$search%")->count();
                $endCount = $offset + $resultCount;
                $morePages = $count > $endCount;

                $results = array(
                    "results" => $data,
                    "pagination" => array(
                        "more" => $morePages
                    )
                );
            }

            return response()->json($results);
        }
    }
}

app/Http/Controllers/Backend/BrandsController.php
<?php

namespace WBstore\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Session;
use Yajra\Datatables\Datatables;
use WBstore\Http\Requests\StoreBrandRequest;
use WBstore\Http\Requests\UpdateBrandRequest;
use WBstore\Brand;

class BrandsController extends Controller
{
    public function index()
    {
        return view('backend.brands.index');
    }

    public function create(Brand $brand)
    {
        return view('backend.brands.create')
            ->with('brand', $brand);
    }

    public function store(StoreBrandRequest $request, Brand $brand)
    {
        $data = $request->all();
        $brand = $brand->create($data);

        return redirect()->route('brands.index')
            ->with('success', 'Бренд "' . $data['title'] . '" успешно добавлен!');
    }

    public function edit(Brand $brand)
    {
        return view('backend.brands.edit', compact('brand'));
    }

    public function update(UpdateBrandRequest $request, Brand $brand)
    {
        $data = $request->all();

        $brand->update($data);

        Session::flash('success', "Информация и бренде '" . $data['title'] . "' обновлена!");

        return back();
        
    }

    public function destroy(Brand $brand)
    {
        if ($brand->exists) {
            if ($brand->image) {
                File::delete($brand->image);
            }
            $brand->delete();
        }
    }

    public function autocomplete(Request $request)
    {
        if (request()->ajax()) {           
            $data = [];

            if ($request->has('term', 'page')) {

                $page = $request->page;
                $resultCount = 10;
                $offset = ($page - 1) * $resultCount;

                $search = $request->term;

                $data = Brand::select("id", "title")->where('title', 'LIKE', "%$search%")->orderBy('title')->skip($offset)->take($resultCount)->get();

                $count = Brand::where('title', 'LIKE', "%$search%")->count();
                $endCount = $offset + $resultCount;
                $morePages = $count > $endCount;

                $results = array(
                    "results" => $data,
                    "pagination" => array(
                        "more" => $morePages
                    )
                );
            }

            return response()->json($results);
        }
    }

    public function datatable()
    {
        if (request()->ajax()) {
            return Datatables::of(Brand::query())
                ->filter(function ($query) {
                    if (!empty(request('search')['value'])) {
                        $query->where('title', 'like', "%" . request('search')['value'] . "%");
                    }
                })
                ->make(true);
        }
    }

}

app/Http/Controllers/Backend/CategoriesController.php
<?php

namespace WBstore\Http\Controllers\Backend;

use Illuminate\Http\Request;
use WBstore\Http\Requests\StoreCategoryRequest;
use WBstore\Http\Requests\UpdateCategoryRequest;
use Yajra\Datatables\Datatables;
use WBstore\Category;
use WBstore\CategoryDescription;
use Illuminate\Support\Facades\DB;
use Session;
use Image;
use File;

class CategoriesController extends Controller
{
    public function index()
    {
		return view('backend.categories.index');
    }

    public function create(Category $category)
    {
		return view('backend.categories.create')
            ->with('category', $category);
    }

    public function store(StoreCategoryRequest $request, Category $category)
    {
        $data = $request->all();

        DB::transaction(function() use ($category, $data) {
    		$newCategory = $category->create($data);
            $newCategory->description()->create($data['description']);
        });

		Session::flash('success', "Категория: '" . $data['description']['title'] . "' успешно добавлена!");

		return redirect()->route('categories.index');
    }

    public function edit(Category $category)
    {
        $category = $category->with('parent')->find($category->id);
        
		return view('backend.categories.edit', compact('category'));
    }

    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $data = $request->all();

        if (!isset($data['parent_id'])) {
            $data['parent_id'] = null;
        }

        DB::transaction(function() use ($category, $data) {
    		$category->update($data);
            $category->description()->update($data['description']);
        });

		Session::flash('success', "Категория: '" . $category->title . "' обновлена!");

		return redirect()->route('categories.index');
    }

    public function destroy(Category $category)
    {
        if ($category->exists) {
            if ($category->image) {
                File::delete($category->image);
            }
            $category->delete();
        }
    }

    public function autocomplete(Request $request)
    {
        if (request()->ajax()) {
            $data = [];

            if ($request->has('term', 'page')) {

                $page = $request->page;
                $resultCount = 10;
                $offset = ($page - 1) * $resultCount;

                $search = $request->term;

                $data = CategoryDescription::select("category_id as id", "title")->where('title', 'LIKE', "%$search%")->orderBy('title')->skip($offset)->take($resultCount)->get();

                $count = CategoryDescription::where('title', 'LIKE', "%$search%")->count();
                $endCount = $offset + $resultCount;
                $morePages = $count > $endCount;

                $results = array(
                    "results" => $data,
                    "pagination" => array(
                        "more" => $morePages
                    )
                );
            }

            return response()->json($results);
        }
    }

    public function datatable()
    {
        if (request()->ajax()) {
            return Datatables::of(Category::formattedCategories())
                ->filter(function ($query) {
                    if (!empty(request('search')['value'])) {
                        $query->where('cd.title', 'like', "%" . request('search')['value'] . "%");
                    }
                })
                ->make(true);
        }
    }

}

app/Http/Controllers/Backend/Controller.php
<?php

namespace WBstore\Http\Controllers\Backend;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function __construct(){}
}

app/Http/Controllers/Backend/DatatablesController.php
<?php

namespace WBstore\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use WBstore\Category;

class DatatablesController extends Controller
{
    public function categories()
    {
        if (request()->ajax()) {
            return Datatables::of(Category::formattedCategories())
                ->filter(function ($query) {
                    if (!empty(request('search')['value'])) {
                        $query->where('cd.title', 'like', "%" . request('search')['value'] . "%");
                    }
                })
                ->make(true);
        }
    }
}

resources/views/backend/products/create.blade.php
@extends('backend.base')

@section('breadcrumbs', Breadcrumbs::render('products.create'))
@section('page-title', 'Добавить товар')

@section('content')
    <!-- BEGIN PlACE PAGE CONTENT HERE -->
    <div class="row">
        <div class="col-md-12">
            @include('backend.products.form')
        </div>
    </div>
    <!-- END PLACE PAGE CONTENT HERE -->
@stop

resources/views/backend/products/edit.blade.php
@extends('backend.base')

@section('breadcrumbs', Breadcrumbs::render('products.edit', $product))
@section('page-title', 'Редактировать товар')

@section('content')
    <!-- BEGIN PlACE PAGE CONTENT HERE -->
    <div class="row">
        <div class="col-md-12">
            @include('backend.products.form')
        </div>
    </div>
    <!-- END PLACE PAGE CONTENT HERE -->
@stop

resources/views/backend/products/index.blade.php
@extends('backend.base')

@section('meta')
    <meta name="csrf-token" content="{{ csrf_token() }}">
@stop

@push('css')
    <link href="/_admin/assets/plugins/jquery-datatables/datatables.min.css" rel="stylesheet" type="text/css">
    <link href="/_admin/assets/plugins/jquery-datatable/css/jquery.dataTables.css" rel="stylesheet" type="text/css">
    <style>
        #products table.table td {vertical-align: middle;}
        #products table.table img {width: 75px;}
    </style>
@endpush

@push('js')
    <script src="/_admin/assets/plugins/jquery-datatables/datatables.min.js" type="text/javascript"></script>
    <script src="/_admin/assets/js/datatable.js" type="text/javascript"></script>

    <script type="text/javascript">

        $(document).ready( function () {
            // Product's DataTable
            $('#products .table').dataTable({
                "dom": "<'row'<'col-md-6'l <'toolbar'>><'col-md-6'f>r>t<'row'<'col-md-12'p i>>",
                "language": <?php include('_admin/assets/plugins/jquery-datatables/datatables.lang.Russian.json'); ?>,
                "order": [[ 2, "asc" ]],
                "processing": true,
                "serverSide": true,
                "ajax": '{!! route('products.datatable') !!}',
                "columns": [{
                        "data": "id",
                        "sortable": false,
                        "searchable": false,
                        "render": function (id, type, full)  {
                            return '<div class="checkbox check-default"><input value="'+id+'" id="checkbox'+id+'" type="checkbox"><label for="checkbox'+id+'"></label></div>';
                        }
                    },{
                        "data": "image",
                        "sortable": false,
                        "searchable": false,
                        "class": "text-center",
                        "render": function (image, type, full)  {
                            if (image) {
                                return '<img src="' + image + '" class="img-thumbnail">';
                            } else {
                                return '';
                            }
                        }
                    },{
                        "data": "description.title",
                    },{
                        "data": "price",
                    },{
                        "data": "status",
                        "searchable": false,
                        "class": "text-center"
                    },{
                        "data": "id",
                        "searchable": false,
                        "sortable": false,
                        "class": "text-right",
                        "render": function (id, type, full)  {
                            var linkDelete = '{!! route("products.destroy", ["products" => '#id_delete']) !!}';
                            var linkEdit = '{!! route("products.edit", ["products" => '#id_edit']) !!}';
                            linkDelete = linkDelete.replace("#id_delete", id);
                            linkEdit = linkEdit.replace("#id_edit", id);
                             
                            return '<a href="'+ linkEdit +'" data-toggle="tooltip" title="" class="btn btn-primary" data-original-title="Редактировать"><i class="fa fa-pencil"></i></a><a href="'+ linkDelete +'" data-toggle="tooltip" data-method="delete" class="postback btn btn-danger" data-original-title="Удалить"><i class="fa fa-trash-o"></i></a>';
                        }
                    }
                ]
            });

            $("div.toolbar").html('<div class="table-tools-actions"><a class="btn btn-primary" href="{{ route("products.create") }}" style="margin-left:12px">Добавить</a></div>');

            $('#products .dataTables_filter input').addClass("input-medium ");
            $('#products .dataTables_length select').removeClass().addClass("select2-wrapper span12");
            $(".select2-wrapper").select2({minimumResultsForSearch: -1});

            // Delete Product
            $(document).on('click', 'a.postback', function(e) {
                e.preventDefault();
                var $this = $(this);
                var data = {
                    url: $this.attr('href'),
                    method: $this.data('method')
                };

                $("#delProduct").click(data, function(e) {
                    var $this = $(this);
                    $("#deleteProductModal").modal('hide');

                    $.ajax({
                        type: data.method,
                        url: data.url,
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    }).done(function (data) {
                        location.reload();
                    });
                });

                $("#deleteProductModal").modal('show');
            });
        });
    </script>
@endpush

@section('breadcrumbs', Breadcrumbs::render('products.index'))
@section('page-title', 'Товары')

@section('content')
    <div class="row-fluid">
        <div class="span12">
            <div class="grid simple ">
                <div class="grid-title">
                    <h4>Cписок товаров</h4>
                    <div class="tools">
                        <a href="javascript:;" class="collapse"></a>
                    </div>
                </div>
                <div class="grid-body ">
                    <div id="products">
                        <div class="row">
                            <div class="col-md-12">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th style="width: 2%"></th>
                                            <th style="width: 4%">Изображение</th>
                                            <th style="width: 58%">Название товара</th>
                                            <th style="width: 5%" class="text-center">Цена</th>
                                            <th style="width: 5%" class="text-center">Статус</th>
                                            <th style="width: 13%" class="text-right">Действие</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="modal fade in" id="deleteProductModal" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <br>
                                    <h4 id="myModalLabel" class="semi-bold">Вы уверены что хотите удалить этот товар?</h4>
                                    <br>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-info" data-dismiss="modal">Отмена</button>
                                    <button type="button" id="delProduct" class="btn btn-danger">Удалить</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop